name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setting up Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.19.0-390.0.dev
      - run: dart pub get
      - run: dart analyze
      - name: Package
        run: ./build.sh
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: nlg_cli-${{ github.ref_name }}.zip
